### PR TITLE
Embed macro

### PR DESCRIPTION
**Pull request by alexkeizer**
I saw this on reddit, and specifically your comment
> I don't know enough about Rust macros to know if it would be possible to create a macro that decodes a character like this and then passes the result on to the compiler. Does anyone know if this is feasible?

Inspired me to give it a go, this PR adds a `zalgo_embed` macro that does exactly this.

### CODE REVIEW

**Comment by alexkeizer** [comment]
The merge conflict is a bit of a red herring.
Because the proc macro needs to be in a separate crate, and I wanted to reuse the `zalgo_decode` function, I moved all existing code to the `common` sub-crate. So, what used to be in `src/lib.rs` is now in `common/src/lib.rs`.
The new lib.rs just publically re-exports all items from both the `common` sub-crate (the existing API) and the `macro` sub-crate, which contains the new `zalgo_embed` macro.

Then, I added some basic tests in the root `lib.rs` using the macro to verify it works.

**Comment by JSorngard** [comment]
This is great! I think it's also that the code in the `common` subcrate is no longer up to date with the code in the main branch (I added a file decoding function). I guess the only thing that needs to be done is updating that code? Also feel free to add yourself to the authors in `Cargo.toml` if you want.

**Comment by alexkeizer** [comment]
It should now be fixed, I took the changes you made to `src/lib.rs` and copied them over to `common/src/lib.rs`

**Comment by JSorngard** [comment]
Excellent! I will merge it in now.

**Pull request merged**
